project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
   # - "docs/topic_modeling.md"
   # - "docs/UNGDC_topic_modeling.qmd"
    - "docs_backup/UNGDC_topic_modeling_updated.qmd"
  execute-dir: project
  
    
website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
   #   - docs/topic_modeling.md
      - docs_backup/UNGDC_topic_modeling_updated.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



