---
title: "COW_war"
author: "Jihyeon bae"
date: "2023-10-21"
output: html_document
---

```{r setup, include=FALSE}
#just a generic list of packages 
library("pacman")
p_load(plyr, dplyr, tidyverse, haven, stevemisc, magrittr, readxl, 
       #for easy data downloading
       peacesciencer)
```


# COW War Data
```{r}
#Download COW War data directly from the peacesciencer package.
cow_civil<-cow_war_intra %>%
  filter(year>=1946) %>%
  distinct(ccodea, year, .keep_all=TRUE) %>%
  filter(ccodea>=0) %>% # ccodea=-8 case (inapplicable because non-state actor)
  select(warnum, wartype, year, cowintraonset, cowintraongoing, ccode=ccodea, intnl)

# panel data template
## Create a template with all countries and years from 1989 to 2022
country_template <- data.frame(
  ccode = rep(unique(cow_civil$ccode), each = 77),
  year = rep(1946:2022, times = n_distinct(cow_civil$ccode))
)

cow_civil <- left_join(country_template, cow_civil, by = c("ccode", "year")) 

cow_civil <- cow_civil %>%
  mutate(cowintraonset=replace_na(cowintraonset, 0),
         cowintraongoing=replace_na(cowintraongoing,0)) %>% # Replace NAs with 0 values 
  group_by(year, ccode) %>%
  summarize(cow_num_civil=sum(cowintraongoing),
            cow_civil=ifelse(cowintraongoing==1|cowintraonset==1, 1, 0))%>%
  arrange(ccode, year)
```
  

# Inter-state War data
```{r}
cow_inter <- cow_war_inter %>%
  select(warnum, year, cowinteronset, cowinterongoing, ccode=ccode1) %>%
  filter(year >= 1946) %>%
  distinct(ccode, year, .keep_all=TRUE) 

cow_inter <- left_join(country_template, cow_inter, by = c("ccode", "year")) 
#this keeps all rows from country_template

cow_inter<-cow_inter %>%
  mutate(cowinteronset=replace_na(cowinteronset, 0),
         cowinterongoing=replace_na(cowinterongoing, 0)) %>%  
  group_by(year, ccode) %>%
  summarize(cow_num_inter=sum(cowinteronset),
            cow_inter=ifelse((cowinterongoing==1|cowinteronset==1), 1, 0))%>%
  arrange(ccode, year)
```
# Merging inter-state and intra-state wars
```{r}
cow_war<-full_join(cow_inter, cow_civil, by=c("ccode", "year"))

# Check for duplicate combinations of year and ccode
duplicate_rows <- cow_war[duplicated(cow_war[c("year", "ccode")]) | 
                     duplicated(cow_war[c("year", "ccode")], fromLast = TRUE), ]

# Print or view the duplicate rows
print(duplicate_rows)
#None! merge complete
```

# Save output as a csv file
```{r}
write.csv(cow_war, "~/Desktop/UNGDC/data/raw/controls/cow_war.csv")
```
`
