---
title: "dpi"
author: "Jihyeon bae"
date: "2023-10-21"
output: html_document
---

```{r setup, include=FALSE}
#just a generic list of packages 
library("pacman")
p_load(plyr, dplyr, lubridate, tidyverse,haven, stevemisc, magrittr, readxl)
```

# Dataset from DPI
```{r}
#World Bank Database of Political Institutions 2020
dpi<-read.csv("DPI2020.csv")

dpi<-dpi%>%
  mutate(year=lubridate::year(year))%>%
  filter(year>=1946)

#Changing DPI countrynames into COW system name.
dpi<-dpi%>%
  mutate(countryname=case_match(countryname, 
             "UAE" ~ "United Arab Emirates",
             "Bosnia-Herz" ~ "Bosnia and Herzegovina",
             "Cent. Af. Rep." ~"Central African Republic",
             "Comoros Is." ~ "Comoros",
             "C. Verde Is." ~ "Cape Verde",
             "Czech Rep." ~ "Czech Republic",
             "Dom. Rep." ~ "Dominican Republic", 
             "UK" ~ "United Kingdom", 
             "Eq. Guinea" ~ "Equatorial Guinea",
             "ROK" ~ "South Korea",
             "Solomon Is." ~ "Solomon Islands",
             "Timor-Leste" ~ "East Timor",
             "Trinidad-Tobago" ~ "Trinidad and Tobago",
             "USA" ~ "United States of America",
             "Yemen (AR)" ~ "Yemen Arab Republic",
             "Yemen (PDR)" ~ "Yemen People's Republic",
             "S. Africa" ~ "South Africa",
             "Congo (DRC)" ~ "Democratic Republic of the Congo",
             "GDR" ~ "German Democratic Republic",
             "PRC" ~ "China",
         .default=countryname))

dpi<-dpi%>%
  mutate(ccode=countrycode(ifs, origin='wb', destination ='cown'))
#Note: column "ifs" is World Bank's own countrycode-very similar but not identical to iso3c

dpi$ccode[dpi$countryname == "Romania"] <- 360 
dpi$ccode[dpi$countryname == "Czech Republic"] <- 316
dpi$ccode[dpi$countryname == "Turk Cyprus"] <- 352
dpi$ccode[dpi$countryname == "German Democratic Republic"] <- 265
dpi$ccode[dpi$countryname == "Soviet Union"] <- 365
dpi$ccode[dpi$countryname == "East Timor"] <- 860
dpi$ccode[dpi$countryname == "Yemen People's Republic"] <- 680
dpi$ccode[dpi$countryname == "Yugoslavia"] <- 345
dpi$ccode[dpi$countryname == "Democratic Republic of the Congo"] <- 490

#eSwatini is dropped. no corresponding COW code. 

dpi<-dpi%>%
  select(ccode, year,
         dpi_execrlc=execrlc, #executive left right center? 1 right 2 center 0 left
         dpi_execnat=execnat, #executive nationalist? 
         dpi_legelec=legelec, #legislative election
         dpi_exelec=exelec, #executive election
         dpi_liec=liec, #legislative electoral competitiveness(higher, more competition)
         dpi_eiec=eiec, #executive electoral competitiveness,
         dpi_fraud=fraud, #vote fraud serious enough? 1 fraud was bad 0 fraud wasn't that bad
         dpi_auton=auton, #autonomous regions
         dpi_muni=muni #municipal gov locally elected
  )


         
```

# Write as a csv file
```{r}
write.csv(dpi, "~/Desktop/UNGDC/data/raw/controls/dpi.csv")
```
