---
title: "Media Control Variables Merging into Master"
author: "Jihyeon Bae"
date: "2023-09-26"
output: 
  html_document:
      number_sections: TRUE
---

```{r setup, include=FALSE}
library("pacman")
p_load(plyr, dplyr, peacesciencer, tidyverse,haven, stevemisc, magrittr, purrr)
```

# Generate COW master data
```{r}
#create all CoW state-years from 1946 to 2022.
cow <- peacesciencer::create_stateyears(system="cow") %>%
  filter(year>=1946&year<2023)%>%
  add_gwcode_to_cow()
  # This adds GW countrycode only where applicable.
```
* variable "ccode" refers to cow country code.
* Key identifiers across ALL the sources are: ccode and year.
* "gwcode" is for reference-only. 

#codes to check the number of countries observed
```{r}
cow %>%
  group_by(statenme, ccode) %>%
  count()#%>%
  #write.csv(file="COW list.csv")
```
* Not all countries are observed every single year from 1989-2022

#Merging
```{r}
#create a list of all dataframes that we need to merge
list<-list(cow, mid, cow_war, qog, protest,
           polity, dpi, navco, pacl, up, vdem)


#repeat the same function over each element of the list
master <- list %>%
  reduce(function(x, y) left_join(x, y, by = c("ccode", "year")))

master<-master%>%
  filter(is.na(ccode)==FALSE)

write.csv(master, "~/Desktop/UNGDC/data/interim/controls.csv")
```

# Checking Data Structure
```{r}
panel_structure <- master %>%
    group_by(year) %>%
    summarise_all(~ sum(!is.na(.)))

# Print the resulting table
print(panel_structure)

library(ggplot2)
library(naniar)

na_plot <- gg_miss_var(master, show_pct = TRUE) +
  theme(
    plot.margin = margin(20, 100, 20, 20, "pt"),
    plot.background = element_rect(fill = "white"),
    text = element_text(family = "Times New Roman")
  )


ggsave("na_plot.png", na_plot, width = 10, height = 15, units = "in")
```

