---
title: "mm_protest"
author: "Jihyeon bae"
date: "2023-10-21"
output: html_document
---

```{r setup, include=FALSE}
#just a generic list of packages 
library("pacman")
p_load(plyr, dplyr, tidyverse, haven, stevemisc, magrittr, readxl, countrycode,
       #for easy data downloading
       peacesciencer)
```

# Mass Mobilization (MM) Protest Data
```{r}
protest<-read_csv("raw_mm_protest.csv") %>%
  filter(year>=1946) %>%
  select(year, polity_ccode=ccode, 
         protest=mm_protest, 
         participants=mm_participants, 
         protesterviolence=mm_protesterviolence) %>%
  mutate(ccode=countrycode::countrycode(polity_ccode, "p4n", "cown")) 
#adding COW code to Polity code
```

# Checking mismatches between Polity and COW country codes
```{r}
# Good justification for manually assigning COW values to GW countries is that I'm copying what Polity is doing. 

View(filter(protest, is.na(ccode)))
# countries that are unambiguously defined: Serbia, West Germany, Ethiopia, Sudan, Vietnam

protest$ccode[protest$polity_ccode == 816] <- 816 # Vietnam has different codes for different time according to Polity system. 
protest$ccode[protest$polity_ccode == 530| protest$polity_ccode==529] <- 530 # Same for Ethiopia

protest$ccode[protest$polity_ccode == 364 & protest$year>=1992] <- 365 # Same for Ethiopia

protest$ccode[protest$polity_ccode == 342 & protest$year>=1992] <- 345 # Same for Serbia 

protest$ccode[protest$polity_ccode == 625 & protest$year>=1992] <- 625 # Same for Sudan 

#renaming variables with source suffix.
protest<-protest %>%
  select(year, ccode, 
         protest, participants, protesterviolence)%>%
  group_by(ccode, year)%>%
  summarise(mm_num_violence=sum(protesterviolence),
            mm_num_protest=sum(protest))
```

# write as a csv file
```{r}
write.csv(protest, "~/Desktop/UNGDC/data/raw/controls/mm_protest.csv")
```

