---
title: "navco"
author: "Jihyeon bae"
date: "2023-10-21"
output: html_document
---

```{r setup, include=FALSE}
#just a generic list of packages 
library("pacman")
p_load(plyr, dplyr, tidyverse, haven, stevemisc, magrittr, readxl, countrycode,
       #for easy data downloading
       peacesciencer)
```

#NAVCO Data focusing on non-violent data
```{r}
navco.original<-read_excel('NAVCO 1.3 List.xlsx') %>%
  filter(BYEAR>=1946) %>%
  dplyr::select(country=LOCATION, year_onset=BYEAR, year_end=EYEAR,
         nonviolent=NONVIOL, violent=VIOL)

#Since NAVCO is also an event-year dataset, I am transforming this into a country-year by expanding year frame.
navco <- navco.original %>%
  mutate(year = map2(year_onset, year_end, ~ seq(.x, .y))) %>%
  unnest(year) %>%
  select(country, year, nonviolent, violent) %>%
  mutate(ccode=countrycode(country, origin = 'country.name', destination = 'cown'))


navco_panel<-navco%>%
  group_by(ccode, year)%>%
  summarize(navco_num_campaign=n())%>%
  mutate(navco_campaign=1)


# Create a template with all countries and years from 1989 to 2019
country_template <- data.frame(
  ccode = rep(unique(navco$ccode), each = 74),
  year = rep(1946:2019, times = n_distinct(navco$ccode))
)

# Perform a left join to ensure each country has 31 rows
navco <- left_join(country_template, navco_panel, by = c("ccode", "year")) 

navco$navco_campaign[is.na(navco$navco_campaign)] <- 0 

navco$navco_num_campaign[is.na(navco$navco_num_campaign)] <- 0 
```

# Save output as a csv file
```{r}
write.csv(navco, "~/Desktop/UNGDC/data/raw/controls/navco.csv")
```
