---
title: "qog"
author: "Jihyeon bae"
date: "2023-10-21"
output: html_document
---

```{r setup, include=FALSE}
#just a generic list of packages 
library("pacman")
p_load(plyr, dplyr, tidyverse, stevemisc, magrittr, readxl, 
       #for easy data downloading
       rqog)
```

# Quality of Government Indicators
```{r}
qog<-read_qog(which_data = "standard", data_type = "time-series")%>%
  filter(year>=1946) 

qog<-qog%>%
  select(fd_regime,
         dd_democracy,
         bmr_dem,
         wdi_homicides, #WDI homicides
  # World Justice Project
         wjp_overall, #WJP Rule of law 
  # World Development Indicators
         wdi_gdpcapcon2015, #WDI gdp 
         wdi_gdpcapgr, #WDI gdp growth rate
         wdi_pop, #WDI total population
  # World Bank Governance Index
         wbgi_rle, #rule of law 
         wbgi_pve, #Political Stability and violence/terrorism 
         wbgi_cce, #estimated control of corruption
         wbgi_gee, # government effectiveness
  # Political Terror Scale
         pts_ptsa=gd_ptsa, 
         pts_ptsh=gd_ptsh, 
         pts_ptss=gd_ptss, 
  # Reporters without border
         rsf_pfi:rsf_pfi1321,
  # Boix Miller Rosato (2022)
         bmr_dem,
  #Globalization Index
         kofgi_dr_eg=dr_eg,
         kofgi_dr_ig=dr_ig,
         kofgi_dr_pg=dr_pg,
         kofgi_dr_sg=dr_sg,
  # NELDA
         nelda_mbbe, #Media bias before election
         nelda_noe, #number of elections
         nelda_oa, # was opposition allowed
         nelda_rpae, # riots and protests after the election
         nelda_vcdbe, #violence and civil deaths before election
  # Identifying variables
         ccode=ccodecow, year)%>%
  mutate(wdi_log_gdpcapcon2015=log(wdi_gdpcapcon2015),
         wdi_log_pop=log(wdi_pop))

#Run below code to check year-availability for each variable
summary(qog[!is.na(qog$nelda_mbbe),])
```

# Save as a csv file
```{r}
write.csv(qog, "~/Desktop/UNGDC/data/raw/controls/qog.csv")
```
